openapi: 3.0.3
info:
  title: Random Events Extended - Get Random Event
  version: 1.0.0
paths:
  /gameplay/world/random-events/{event_id}:
    get:
      summary: Получить детали события
      operationId: getRandomEvent
      tags:
        - Random Events
      security:
        - BearerAuth: []
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Детали события
          content:
            application/json:
              schema:
                $ref: '../schemas/index.yaml#/components/schemas/RandomEventDetailed'
        '401':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/NotFound'
        '400':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/InternalServerError'

