openapi: 3.0.3
info:
  title: Trigger Random Event
  version: 1.0.0
paths:
  /gameplay/world/random-events/trigger:
    post:
      summary: Триггернуть случайное событие
      operationId: triggerRandomEvent
      tags:
        - Event Triggers
      description: Используется backend системами для генерации событий
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/index.yaml#/components/schemas/TriggerEventRequest'
      responses:
        '200':
          description: Событие триггернуто
          content:
            application/json:
              schema:
                $ref: '../schemas/index.yaml#/components/schemas/TriggeredEventInstance'
        '400':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/NotFound'
        '409':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/Conflict'
        '500':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/InternalServerError'

