# Personal NPC Tool API - Аудит и события
# Источник: .BRAIN/02-gameplay/social/personal-npc-tool.md (v1.0.0)
# Раздел: Endpoints для аудита, событий и журнала операций

openapi: 3.0.3
info:
  title: Personal NPC Tool - Audit & Events
  version: 1.0.0
  description: |
    Endpoints для аудита, событий и журнала операций.
    Источник: .BRAIN/02-gameplay/social/personal-npc-tool.md (v1.0.0)

paths:
  # Аудит и журнал операций
  /gameplay/social/npc/audit:
    get:
      summary: Получить логи аудита
      description: |
        Возвращает логи аудита для указанных параметров.
        Все изменения в системе записываются в AuditLog.
      operationId: getAuditLogs
      tags: [Audit]
      security:
        - BearerAuth: []
      parameters:
        - name: owner_id
          in: query
          schema: {type: string, format: uuid}
        - name: entity_type
          in: query
          schema: {type: string, enum: [npc, scenario, contract, license, owner]}
        - name: entity_id
          in: query
          schema: {type: string, format: uuid}
        - name: action
          in: query
          schema: {type: string, enum: [create, update, delete, start, stop, transfer, breach, fulfill]}
        - name: actor_id
          in: query
          schema: {type: string, format: uuid}
        - name: from
          in: query
          schema: {type: string, format: date-time}
        - name: to
          in: query
          schema: {type: string, format: date-time}
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/Page'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: Список записей аудита
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../personal-npc-tool-models-3.yaml#/components/schemas/AuditLog'
                  meta:
                    $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginationMeta'
        '400': {$ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'}
        '500': {$ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'}

  /gameplay/social/npc/ledger:
    get:
      summary: Получить журнал операций
      description: |
        Возвращает журнал финансовых операций (Ledger).
        Все финансовые операции записываются в Ledger.
      operationId: getLedger
      tags: [Ledger]
      security:
        - BearerAuth: []
      parameters:
        - name: owner_id
          in: query
          schema: {type: string, format: uuid}
        - name: npc_id
          in: query
          schema: {type: string, format: uuid}
        - name: scenario_id
          in: query
          schema: {type: string, format: uuid}
        - name: type
          in: query
          schema: {type: string, enum: [cost, reward, payment, transfer, fee]}
        - name: from
          in: query
          schema: {type: string, format: date-time}
        - name: to
          in: query
          schema: {type: string, format: date-time}
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/Page'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: Список финансовых операций
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../personal-npc-tool-models-3.yaml#/components/schemas/Ledger'
                  meta:
                    $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginationMeta'
        '400': {$ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'}
        '500': {$ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'}

  # События и подписки
  /gameplay/social/npc/events:
    get:
      summary: Получить список событий
      operationId: getEvents
      tags: [Events]
      security:
        - BearerAuth: []
      parameters:
        - name: owner_id
          in: query
          schema: {type: string, format: uuid}
        - name: entity_type
          in: query
          schema: {type: string, enum: [npc, scenario, contract, license, owner]}
        - name: entity_id
          in: query
          schema: {type: string, format: uuid}
        - name: event_type
          in: query
          schema: {type: string}
        - name: from
          in: query
          schema: {type: string, format: date-time}
        - name: to
          in: query
          schema: {type: string, format: date-time}
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/Page'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: Список событий
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../personal-npc-tool-models-3.yaml#/components/schemas/Event'
                  meta:
                    $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginationMeta'
        '400': {$ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'}
        '500': {$ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'}

  /gameplay/social/npc/events/subscribe:
    post:
      summary: Подписаться на события
      operationId: subscribeToEvents
      tags: [Events]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../personal-npc-tool-requests.yaml#/components/schemas/SubscribeRequest'
      responses:
        '201':
          description: Подписка создана
          content:
            application/json:
              schema:
                $ref: '../personal-npc-tool-models-3.yaml#/components/schemas/Subscription'
        '400': {$ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'}
        '403': {$ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'}
        '500': {$ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'}

  /gameplay/social/npc/events/subscriptions/{subscription_id}:
    delete:
      summary: Отписаться от событий
      operationId: unsubscribeFromEvents
      tags: [Events]
      security:
        - BearerAuth: []
      parameters:
        - name: subscription_id
          in: path
          required: true
          schema: {type: string, format: uuid}
      responses:
        '204': {description: Подписка удалена}
        '403': {$ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'}
        '404': {$ref: '../../shared/common/responses.yaml#/components/responses/NotFound'}
        '500': {$ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'}

