# Personal NPC Tool API - Request/Response модели
# Источник: .BRAIN/02-gameplay/social/personal-npc-tool.md (v1.0.0)

openapi: 3.0.3
info:
  title: Personal NPC Tool - Request/Response Models
  version: 1.0.0

components:
  schemas:
    # Request модели для NPC
    CreateNPCRequest:
      type: object
      required:
        - owner_id
        - name
        - type
      description: Запрос на создание NPC
      properties:
        owner_id:
          type: string
          format: uuid
          description: Идентификатор владельца
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Имя NPC
          example: "John Doe"
        type:
          type: string
          enum: [human, robot, android]
          description: Тип NPC
          example: "human"
        initial_role:
          type: object
          nullable: true
          description: Начальная роль для назначения
          properties:
            role_id:
              type: string
            priority:
              type: integer
              minimum: 1
              maximum: 10

    UpdateNPCRequest:
      type: object
      description: Запрос на обновление NPC (все поля опциональны)
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Имя NPC
        specializations:
          type: array
          items:
            type: string
          description: Специализации NPC

    AssignRoleRequest:
      type: object
      required:
        - role_id
        - priority
      description: Запрос на назначение роли
      properties:
        role_id:
          type: string
          description: Идентификатор роли
          example: "guard"
        priority:
          type: integer
          minimum: 1
          maximum: 10
          description: Приоритет роли
          example: 5
        conditions:
          type: object
          nullable: true
          description: Условия активации роли
          additionalProperties: true

    MaintenanceRequest:
      type: object
      required:
        - type
      description: Запрос на обслуживание NPC
      properties:
        type:
          type: string
          enum: [routine, urgent, emergency]
          description: Тип обслуживания
          example: "routine"
        urgency:
          type: string
          enum: [low, medium, high]
          description: Срочность обслуживания
          example: "medium"

    MaintenanceResult:
      type: object
      required:
        - cost
        - duration
        - effects
      description: Результат обслуживания NPC
      properties:
        cost:
          type: number
          format: float
          minimum: 0
          description: Стоимость обслуживания
          example: 100.0
        duration:
          type: number
          format: float
          minimum: 0
          description: Длительность обслуживания (сек)
          example: 3600.0
        effects:
          type: object
          description: Эффекты обслуживания {health: float, energy: float}
          additionalProperties:
            type: number
          example:
            health: 100.0
            energy: 100.0

    # Request модели для сценариев
    CreateBlueprintRequest:
      type: object
      required:
        - name
        - description
        - category
        - steps
      description: Запрос на создание блупринта сценария
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
          description: Название сценария
          example: "Охрана склада"
        description:
          type: string
          description: Описание сценария
          example: "Сценарий охраны склада с периодическими патрулями"
        category:
          type: string
          enum: [economy, social, combat, logistics]
          description: Категория сценария
          example: "combat"
        required_roles:
          type: array
          items:
            type: string
          description: Требуемые роли для выполнения сценария
          example: ["guard"]
        steps:
          type: array
          items:
            type: object
          description: Набор шагов/правил сценария
        parameters:
          type: object
          nullable: true
          description: Параметры сценария
          additionalProperties: true
        conditions:
          type: object
          nullable: true
          description: Условия запуска сценария
          additionalProperties: true
        is_public:
          type: boolean
          default: false
          description: Публичный ли блупринт
          example: false
        price:
          type: number
          format: float
          nullable: true
          minimum: 0
          description: Цена блупринта (если продается)
          example: null

    UpdateBlueprintRequest:
      type: object
      description: Запрос на обновление блупринта (все поля опциональны)
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
        version:
          type: string
        steps:
          type: array
          items:
            type: object

    CreateInstanceRequest:
      type: object
      required:
        - blueprint_id
        - npc_id
        - owner_id
      description: Запрос на создание инстанса сценария
      properties:
        blueprint_id:
          type: string
          format: uuid
          description: Идентификатор блупринта
          example: "770e8400-e29b-41d4-a716-446655440001"
        npc_id:
          type: string
          format: uuid
          description: Идентификатор NPC
          example: "660e8400-e29b-41d4-a716-446655440001"
        owner_id:
          type: string
          format: uuid
          description: Идентификатор владельца
          example: "550e8400-e29b-41d4-a716-446655440000"
        parameters:
          type: object
          nullable: true
          description: Параметры инстанса
          additionalProperties: true
        scheduled_at:
          type: string
          format: date-time
          nullable: true
          description: Запланированное время запуска
          example: null

    CancelInstanceRequest:
      type: object
      description: Запрос на отмену инстанса
      properties:
        reason:
          type: string
          description: Причина отмены
          example: "Изменение планов"

    # Request модели для контрактов
    CreateContractRequest:
      type: object
      required:
        - type
        - npc_id
        - from_owner_id
        - to_owner_id
        - terms
      description: Запрос на создание контракта
      properties:
        type:
          type: string
          enum: [ownership_transfer, lease, loan]
          description: Тип контракта
          example: "lease"
        npc_id:
          type: string
          format: uuid
          description: Идентификатор NPC
          example: "660e8400-e29b-41d4-a716-446655440001"
        from_owner_id:
          type: string
          format: uuid
          description: Идентификатор текущего владельца
          example: "550e8400-e29b-41d4-a716-446655440000"
        to_owner_id:
          type: string
          format: uuid
          description: Идентификатор нового владельца/арендатора
          example: "550e8400-e29b-41d4-a716-446655440002"
        terms:
          type: object
          description: Условия контракта
          properties:
            duration:
              type: number
              format: float
            payment:
              type: object
            obligations:
              type: array
              items:
                type: object
            rights:
              type: object
          additionalProperties: true

    CancelContractRequest:
      type: object
      description: Запрос на отмену контракта
      properties:
        reason:
          type: string
          description: Причина отмены
          example: "Соглашение расторгнуто"

    BreachContractRequest:
      type: object
      description: Запрос на нарушение контракта
      properties:
        reason:
          type: string
          description: Причина нарушения
          example: "Невыполнение обязательств"
        penalties:
          type: object
          nullable: true
          description: Штрафы за нарушение
          additionalProperties: true

    # Request модели для лицензий
    SuspendLicenseRequest:
      type: object
      required:
        - reason
      description: Запрос на приостановку лицензии
      properties:
        reason:
          type: string
          description: Причина приостановки
          example: "Нарушение условий"

    # Request модели для событий
    SubscribeRequest:
      type: object
      required:
        - event_types
        - notification_method
      description: Запрос на подписку на события
      properties:
        event_types:
          type: array
          items:
            type: string
          description: Типы событий для подписки
          example: ["npc.status_changed", "scenario.completed"]
        filters:
          type: object
          nullable: true
          description: Фильтры для событий
          additionalProperties: true
        notification_method:
          type: string
          enum: [webhook, email, in_game]
          description: Метод уведомления
          example: "webhook"
        webhook_url:
          type: string
          format: uri
          nullable: true
          description: URL вебхука (если notification_method=webhook)
          example: "https://example.com/webhook"

