# Personal NPC Tool API - Главный файл
# Источник: .BRAIN/02-gameplay/social/personal-npc-tool.md (v1.0.0)
# Задание: API-SWAGGER/tasks/active/queue/task-001-personal-npc-tool-api.md
# Task ID: API-TASK-001

openapi: 3.0.3
info:
  title: Personal NPC Tool API
  version: 1.0.0
  description: |
    # API для системы персональных NPC
    
    ## Описание
    
    Система персональных NPC позволяет игрокам и кланам нанимать, настраивать и использовать NPC 
    для выполнения задач в экономике, социальных и боевых сценариях.
    
    ## Источники
    
    - Оригинальный документ: `.BRAIN/02-gameplay/social/personal-npc-tool.md`
    - Версия документа: v1.0.0
    - Задание: `API-SWAGGER/tasks/active/queue/task-001-personal-npc-tool-api.md`
    - Task ID: API-TASK-001
    
    ## Структура API
    
    API разбито на несколько файлов для удобства поддержки:
    - Управление NPC: `personal-npc-tool-npc.yaml`
    - Управление сценариями: `personal-npc-tool-scenarios.yaml`
    - Контракты: `personal-npc-tool-contracts.yaml`
    - Лицензии: `personal-npc-tool-licenses.yaml`
    - Аудит и события: `personal-npc-tool-audit.yaml`
    - Модели данных: `personal-npc-tool-models.yaml`
    
    ## Комментарии для исполнителя
    
    - Все данные хранятся в БД PostgreSQL
    - Валидация выполняется на бекенде
    - Все операции проверяют права доступа (матрица прав: Ownership → Administration → Delegation → Observation)
    - Все операции проверяют лимиты владельца (зависят от лицензий L1, L2, L3 и репутации)
    - Все изменения записываются в AuditLog
    - Все финансовые операции записываются в Ledger

servers:
  - url: https://api.necp.game/v1
    description: Production server

paths:
  # Все endpoints определены в отдельных файлах через $ref
  # См. personal-npc-tool-npc.yaml, personal-npc-tool-scenarios.yaml и т.д.

components:
  # Импорт схем из отдельных файлов
  schemas:
    # Модели импортируются из personal-npc-tool-models.yaml
    Owner:
      $ref: './personal-npc-tool-models.yaml#/components/schemas/Owner'
    PersonalNPC:
      $ref: './personal-npc-tool-models.yaml#/components/schemas/PersonalNPC'
    RoleAssignment:
      $ref: './personal-npc-tool-models.yaml#/components/schemas/RoleAssignment'
    NPCStats:
      $ref: './personal-npc-tool-models.yaml#/components/schemas/NPCStats'
    NPCCosts:
      $ref: './personal-npc-tool-models.yaml#/components/schemas/NPCCosts'
    RoleSet:
      $ref: './personal-npc-tool-models.yaml#/components/schemas/RoleSet'
    ScenarioBlueprint:
      $ref: './personal-npc-tool-models-2.yaml#/components/schemas/ScenarioBlueprint'
    ScenarioStep:
      $ref: './personal-npc-tool-models-2.yaml#/components/schemas/ScenarioStep'
    ScenarioInstance:
      $ref: './personal-npc-tool-models-2.yaml#/components/schemas/ScenarioInstance'
    ScenarioKPI:
      $ref: './personal-npc-tool-models-2.yaml#/components/schemas/ScenarioKPI'
    Contract:
      $ref: './personal-npc-tool-models-2.yaml#/components/schemas/Contract'
    ContractTerms:
      $ref: './personal-npc-tool-models-2.yaml#/components/schemas/ContractTerms'
    License:
      $ref: './personal-npc-tool-models-3.yaml#/components/schemas/License'
    Certificate:
      $ref: './personal-npc-tool-models-3.yaml#/components/schemas/Certificate'
    AuditLog:
      $ref: './personal-npc-tool-models-3.yaml#/components/schemas/AuditLog'
    Ledger:
      $ref: './personal-npc-tool-models-3.yaml#/components/schemas/Ledger'
    Event:
      $ref: './personal-npc-tool-models-3.yaml#/components/schemas/Event'
    Subscription:
      $ref: './personal-npc-tool-models-3.yaml#/components/schemas/Subscription'
    
    # Request/Response модели
    CreateNPCRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/CreateNPCRequest'
    UpdateNPCRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/UpdateNPCRequest'
    AssignRoleRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/AssignRoleRequest'
    CreateBlueprintRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/CreateBlueprintRequest'
    UpdateBlueprintRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/UpdateBlueprintRequest'
    CreateInstanceRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/CreateInstanceRequest'
    CancelInstanceRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/CancelInstanceRequest'
    CreateContractRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/CreateContractRequest'
    CancelContractRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/CancelContractRequest'
    BreachContractRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/BreachContractRequest'
    SuspendLicenseRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/SuspendLicenseRequest'
    SubscribeRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/SubscribeRequest'
    MaintenanceRequest:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/MaintenanceRequest'
    MaintenanceResult:
      $ref: './personal-npc-tool-requests.yaml#/components/schemas/MaintenanceResult'
    Limits:
      $ref: './personal-npc-tool-models.yaml#/components/schemas/Limits'
  
  # Импорт стандартных ответов
  responses:
    BadRequest:
      $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
    Unauthorized:
      $ref: '../../shared/common/responses.yaml#/components/responses/Unauthorized'
    Forbidden:
      $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
    NotFound:
      $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
    Conflict:
      $ref: '../../shared/common/responses.yaml#/components/responses/Conflict'
    UnprocessableEntity:
      $ref: '../../shared/common/responses.yaml#/components/responses/UnprocessableEntity'
    InternalServerError:
      $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'
  
  # Импорт схем безопасности
  securitySchemes:
    BearerAuth:
      $ref: '../../shared/common/security.yaml#/components/securitySchemes/BearerAuth'

