# Personal NPC Tool API - Управление NPC
# Источник: .BRAIN/02-gameplay/social/personal-npc-tool.md (v1.0.0)
# Раздел: Endpoints для управления NPC

openapi: 3.0.3
info:
  title: Personal NPC Tool - NPC Management
  version: 1.0.0
  description: |
    Endpoints для управления NPC.
    Источник: .BRAIN/02-gameplay/social/personal-npc-tool.md (v1.0.0)

paths:
  # Управление NPC
  /gameplay/social/npc:
    post:
      summary: Создать нового NPC
      description: |
        Создает нового персонального NPC для указанного владельца.
        Проверяет лимиты владельца (maxNPCs), права доступа и лицензии.
        При создании NPC автоматически назначается базовая роль (если указана).
        Источник: .BRAIN/02-gameplay/social/personal-npc-tool.md -> PersonalNPC
      operationId: createNPC
      tags:
        - NPC
        - Management
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../personal-npc-tool-requests.yaml#/components/schemas/CreateNPCRequest'
            examples:
              create_human_npc:
                summary: Создать человеческого NPC
                value:
                  owner_id: "550e8400-e29b-41d4-a716-446655440000"
                  name: "John Doe"
                  type: "human"
                  initial_role:
                    role_id: "guard"
                    priority: 5
      responses:
        '201':
          description: NPC успешно создан
          content:
            application/json:
              schema:
                $ref: '../personal-npc-tool-models.yaml#/components/schemas/PersonalNPC'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '409':
          description: Превышен лимит NPC для владельца
          content:
            application/json:
              schema:
                $ref: '../../shared/common/responses.yaml#/components/schemas/Error'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

    get:
      summary: Получить список NPC владельца
      description: |
        Возвращает список NPC владельца с возможностью фильтрации по статусу и типу.
      operationId: listNPCs
      tags:
        - NPC
      security:
        - BearerAuth: []
      parameters:
        - name: owner_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор владельца
        - name: status
          in: query
          schema:
            type: string
            enum: [idle, working, resting, training, maintenance]
          description: Фильтр по статусу NPC
        - name: type
          in: query
          schema:
            type: string
            enum: [human, robot, android]
          description: Фильтр по типу NPC
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/Page'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: Список NPC
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../personal-npc-tool-models.yaml#/components/schemas/PersonalNPC'
                  meta:
                    $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginationMeta'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/social/npc/{npc_id}:
    get:
      summary: Получить информацию о NPC
      description: Возвращает полную информацию о NPC, включая роли, характеристики и расходы.
      operationId: getNPC
      tags:
        - NPC
      security:
        - BearerAuth: []
      parameters:
        - name: npc_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор NPC
      responses:
        '200':
          description: Информация о NPC
          content:
            application/json:
              schema:
                $ref: '../personal-npc-tool-models.yaml#/components/schemas/PersonalNPC'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

    put:
      summary: Обновить информацию о NPC
      description: Обновляет информацию о NPC (частичное обновление). Проверяет права доступа.
      operationId: updateNPC
      tags:
        - NPC
        - Management
      security:
        - BearerAuth: []
      parameters:
        - name: npc_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор NPC
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../personal-npc-tool-requests.yaml#/components/schemas/UpdateNPCRequest'
      responses:
        '200':
          description: NPC успешно обновлен
          content:
            application/json:
              schema:
                $ref: '../personal-npc-tool-models.yaml#/components/schemas/PersonalNPC'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '422':
          $ref: '../../shared/common/responses.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

    delete:
      summary: Удалить NPC
      description: Удаляет NPC. Проверяет права доступа. Все связанные сценарии и контракты должны быть завершены.
      operationId: deleteNPC
      tags:
        - NPC
        - Management
      security:
        - BearerAuth: []
      parameters:
        - name: npc_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор NPC
      responses:
        '204':
          description: NPC успешно удален
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '422':
          description: Невозможно удалить NPC (есть активные сценарии или контракты)
          content:
            application/json:
              schema:
                $ref: '../../shared/common/responses.yaml#/components/schemas/Error'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/social/npc/{npc_id}/roles:
    post:
      summary: Назначить роль NPC
      description: Назначает роль NPC. Проверяет права доступа и доступность роли.
      operationId: assignRole
      tags:
        - NPC
        - Roles
      security:
        - BearerAuth: []
      parameters:
        - name: npc_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор NPC
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../personal-npc-tool-requests.yaml#/components/schemas/AssignRoleRequest'
      responses:
        '201':
          description: Роль успешно назначена
          content:
            application/json:
              schema:
                $ref: '../personal-npc-tool-models.yaml#/components/schemas/RoleAssignment'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '409':
          description: Роль уже назначена или превышен лимит ролей
          content:
            application/json:
              schema:
                $ref: '../../shared/common/responses.yaml#/components/schemas/Error'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/social/npc/{npc_id}/roles/{role_id}:
    delete:
      summary: Удалить роль у NPC
      description: |
        Удаляет роль у NPC. Проверяет права доступа (Administration или выше).
        Если роль используется в активном сценарии, операция может быть отклонена.
      operationId: removeRole
      tags:
        - NPC
        - Roles
      security:
        - BearerAuth: []
      parameters:
        - name: npc_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор NPC
        - name: role_id
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор роли
      responses:
        '204':
          description: Роль успешно удалена
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '422':
          description: Невозможно удалить роль (используется в активном сценарии)
          content:
            application/json:
              schema:
                $ref: '../../shared/common/responses.yaml#/components/schemas/Error'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/social/npc/{npc_id}/stats:
    get:
      summary: Получить статистику NPC
      description: Возвращает характеристики NPC (навыки, эффективность, лояльность, здоровье, энергия, стресс).
      operationId: getNPCStats
      tags:
        - NPC
      security:
        - BearerAuth: []
      parameters:
        - name: npc_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор NPC
      responses:
        '200':
          description: Статистика NPC
          content:
            application/json:
              schema:
                $ref: '../personal-npc-tool-models.yaml#/components/schemas/NPCStats'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/social/npc/{npc_id}/costs:
    get:
      summary: Получить текущие расходы на содержание NPC
      description: Возвращает текущие расходы на содержание NPC. Зависят от типа NPC и ролей.
      operationId: getNPCCosts
      tags:
        - NPC
        - Economy
      security:
        - BearerAuth: []
      parameters:
        - name: npc_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор NPC
      responses:
        '200':
          description: Расходы на содержание NPC
          content:
            application/json:
              schema:
                $ref: '../personal-npc-tool-models.yaml#/components/schemas/NPCCosts'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/social/npc/{npc_id}/maintenance:
    post:
      summary: Выполнить обслуживание NPC
      description: Выполняет обслуживание NPC. Восстанавливает характеристики. Записывает в Ledger.
      operationId: performMaintenance
      tags:
        - NPC
        - Management
      security:
        - BearerAuth: []
      parameters:
        - name: npc_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор NPC
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../personal-npc-tool-requests.yaml#/components/schemas/MaintenanceRequest'
      responses:
        '200':
          description: Обслуживание выполнено
          content:
            application/json:
              schema:
                $ref: '../personal-npc-tool-requests.yaml#/components/schemas/MaintenanceResult'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

