openapi: 3.0.3
info:
  title: Attributes D&D Mapping API
  version: 1.0.0
  description: |
    API для маппинга атрибутов Cyberpunk на D&D систему.
    
    Источник: .BRAIN/02-gameplay/combat/combat-dnd-core.md v1.1.0
    
    Cyberpunk атрибуты → D&D:
    - BODY → Strength/Constitution
    - REFLEX → Dexterity
    - TECH → Intelligence (tech)
    - INTELLIGENCE → Intelligence (knowledge)
    - COOL → Wisdom/Charisma

  x-microservice:
    name: world-service
    port: 8086
    domain: world
    base-path: /api/v1/gameplay/world
    package: com.necpgame.worldservice
servers:
  - url: https://api.necp.game/v1
    description: Production API Gateway
  - url: http://localhost:8080/api/v1
    description: Local API Gateway

tags:
  - name: Attributes Mapping
    description: Маппинг атрибутов

paths:
  /gameplay/world/attributes-mapping:
    get:
      summary: Получить маппинг атрибутов
      description: Возвращает соответствие Cyberpunk атрибутов D&D системе
      operationId: getAttributesMapping
      tags:
        - Attributes Mapping
      responses:
        '200':
          description: Маппинг атрибутов
          content:
            application/json:
              schema:
                type: object

  /gameplay/world/attributes-mapping/calculate:
    post:
      summary: Рассчитать D&D модификаторы
      description: Преобразует Cyberpunk атрибуты в D&D модификаторы
      operationId: calculateDnDModifiers
      tags:
        - Attributes Mapping
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: integer
                reflex:
                  type: integer
                tech:
                  type: integer
                intelligence:
                  type: integer
                cool:
                  type: integer
      responses:
        '200':
          description: D&D модификаторы
          content:
            application/json:
              schema:
                type: object

components:
  schemas: {}


