openapi: 3.0.3
info:
  title: Notifications Examples
  version: 1.0.0
paths: {}
components:
  examples:
    QuestCompleteSend:
      summary: Отправка push уведомления о завершении квеста
      value:
        recipientId: "player-42af"
        channel: "PUSH"
        templateId: "quest-complete-v1"
        locale: "ru-RU"
        data:
          questName: "Blackwall Recon"
          rewardCredits: 500
          rewardItem: "cyber-mod-alpha"
        idempotencyKey: "quest-42af-20251107"
        priority: "HIGH"
    PreferencesUpdate:
      summary: Обновление предпочтений и тихих часов
      value:
        channels:
          - channel: "IN_GAME"
            enabled: true
            frequency: "INSTANT"
          - channel: "PUSH"
            enabled: true
            frequency: "INSTANT"
          - channel: "EMAIL"
            enabled: false
        categories:
          - category: "guild"
            enabled: true
          - category: "marketing"
            enabled: false
        mutedUntil: null
