openapi: 3.0.3
info:
  title: Friend Examples
  version: 1.0.0
paths: {}
components:
  examples:
    FriendRequestCreate:
      summary: Запрос в друзья по никнейму
      value:
        target:
          nickname: "Glitch"
          platform: "PC"
        message: "Давай сыграем завтра!"
        idempotencyKey: "friend-request-neo-glitch-20251108"
    PresenceUpdateRequest:
      summary: Обновление статуса присутствия
      value:
        state: "IN_MATCH"
        activity: "Night City Raid"
        sessionId: "session-87231"
        availability: "BUSY"
