openapi: 3.0.3
info:
  title: Crafting System - Calculate Crafting Chance
  version: 1.0.0
paths:
  /gameplay/economy/crafting/calculate:
    post:
      summary: Рассчитать шанс успеха и время крафта
      operationId: calculateCraftingChance
      tags: [Crafting]
      description: Для UI - показать перед крафтом
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                character_id:
                  type: string
                  format: uuid
                recipe_id:
                  type: string
                station_id:
                  type: string
                  nullable: true
      responses:
        '200':
          description: Расчет крафта
          content:
            application/json:
              schema:
                $ref: '../schemas/index.yaml#/components/schemas/CraftingCalculation'
        '400': { $ref: '../../../../shared/common/responses.yaml#/components/responses/BadRequest' }
        '401': { $ref: '../../../../shared/common/responses.yaml#/components/responses/Unauthorized' }
        '404': { $ref: '../../../../shared/common/responses.yaml#/components/responses/NotFound' }
        '500': { $ref: '../../../../shared/common/responses.yaml#/components/responses/InternalServerError' }

