openapi: 3.0.3
info:
  title: Crafting System - Craft Item
  version: 1.0.0
paths:
  /gameplay/economy/crafting/craft:
    post:
      summary: Крафтнуть предмет
      operationId: craftItem
      tags: [Crafting]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/index.yaml#/components/schemas/CraftRequest'
      responses:
        '200':
          description: Крафт начат
          content:
            application/json:
              schema:
                $ref: '../schemas/index.yaml#/components/schemas/CraftingSession'
        '400':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/NotFound'
        '422':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/InternalServerError'

