openapi: 3.0.3
info:
  title: Crafting System - Get Crafting Session
  version: 1.0.0
paths:
  /gameplay/economy/crafting/sessions/{session_id}:
    get:
      summary: Получить статус крафтинга
      operationId: getCraftingSession
      tags: [Crafting]
      security:
        - BearerAuth: []
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Статус сессии
          content:
            application/json:
              schema:
                $ref: '../schemas/index.yaml#/components/schemas/CraftingSession'
        '404':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/NotFound'
        '401':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/Unauthorized'
        '400':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../../../shared/common/responses.yaml#/components/responses/InternalServerError'

