openapi: 3.0.3
info:
  title: Economy World Impact API
  version: 1.0.0
  description: API для влияния экономики на мир (динамические цены, дефицит, события)
servers:
  - url: https://api.necp.game/v1
tags:
  - name: Economy World Impact
paths:
  /gameplay/economy/world-impact:
    get:
      summary: Получить влияние экономики на мир
      operationId: getEconomyWorldImpact
      tags: [Economy World Impact]
      responses:
        '200':
          description: Влияние экономики
          content:
            application/json:
              schema:
                type: object
components:
  schemas: {}


