openapi: 3.0.3
info:
  title: Monetization API
  version: 1.0.0
  description: API для монетизации (Premium currency, Battle Pass, Cosmetics)
servers:
  - url: https://api.necp.game/v1
tags:
  - name: Monetization
paths:
  /gameplay/economy/monetization/premium-currency:
    get:
      summary: Получить баланс премиум валюты
      operationId: getPremiumCurrency
      tags: [Monetization]
      parameters:
        - name: character_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Баланс премиум валюты
          content:
            application/json:
              schema:
                type: object
components:
  schemas: {}


