# Character Creation API - Справочные модели
# Источник: .BRAIN/05-technical/ui-character-creation.md (v1.1.0)
# Задание: API-SWAGGER/tasks/active/queue/task-026-character-creation-api.md
# Task ID: API-TASK-026

openapi: 3.0.3
info:
  title: Character Creation API - Reference Models
  version: 1.0.0
  description: |
    Справочные модели данных для API начального интерфейса (классы, происхождения, фракции, города, внешность).
    Используется через $ref в главном файле character-creation.yaml.

paths: {}

components:
  schemas:
    # Модель внешности персонажа
    GameCharacterAppearance:
      type: object
      required:
        - height
        - body_type
        - hair_color
        - eye_color
        - skin_color
      properties:
        height:
          type: integer
          minimum: 150
          maximum: 220
          description: Рост в см
          example: 180
        body_type:
          type: string
          enum: [thin, normal, muscular, large]
          description: Телосложение
          example: "normal"
        hair_color:
          type: string
          description: Цвет волос
          example: "black"
        eye_color:
          type: string
          description: Цвет глаз
          example: "brown"
        skin_color:
          type: string
          description: Цвет кожи
          example: "light"
        distinctive_features:
          type: string
          maxLength: 500
          nullable: true
          description: Особые приметы (максимум 500 символов)
          example: "Scar on left cheek"
    
    # Справочные модели
    GameCharacterClass:
      type: object
      required:
        - id
        - name
        - description
        - subclasses
      properties:
        id:
          type: string
          description: Идентификатор класса
          example: "solo"
        name:
          type: string
          description: Название класса
          example: "Solo"
        description:
          type: string
          description: Описание класса
          example: "Боевой класс, специализация на боевых навыках"
        subclasses:
          type: array
          description: Список подклассов
          items:
            type: object
            required:
              - id
              - name
              - description
            properties:
              id:
                type: string
                description: Идентификатор подкласса
                example: "solo_assassin"
              name:
                type: string
                description: Название подкласса
                example: "Assassin"
              description:
                type: string
                description: Описание подкласса
                example: "Специализация на скрытности и убийствах"
    
    GameCharacterOrigin:
      type: object
      required:
        - id
        - name
        - description
        - starting_skills
        - available_factions
        - starting_resources
      properties:
        id:
          type: string
          enum: [street_kid, corpo, nomad]
          description: Идентификатор происхождения
          example: "street_kid"
        name:
          type: string
          description: Название происхождения
          example: "Уличный бродяга"
        description:
          type: string
          description: Описание происхождения
          example: "Вырос на улицах, выживание любой ценой"
        starting_skills:
          type: array
          description: Список стартовых навыков
          items:
            type: string
          example: ["street_combat", "survival"]
        available_factions:
          type: array
          description: Список доступных фракций (UUID)
          items:
            type: string
            format: uuid
          example: ["550e8400-e29b-41d4-a716-446655440000"]
        starting_resources:
          type: object
          required:
            - currency
            - items
          properties:
            currency:
              type: integer
              description: Стартовая валюта
              example: 1000
            items:
              type: array
              description: Список стартовых предметов
              items:
                type: string
              example: ["basic_pistol", "street_clothes"]
    
    Faction:
      type: object
      required:
        - id
        - name
        - type
        - description
        - available_for_origins
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор фракции
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: Название фракции
          example: "Arasaka"
        type:
          type: string
          enum: [corporation, gang, organization]
          description: Тип фракции
          example: "corporation"
        description:
          type: string
          description: Описание фракции
          example: "Корпорация, технологии, власть"
        available_for_origins:
          type: array
          description: Список доступных происхождений для старта
          items:
            type: string
            enum: [street_kid, corpo, nomad]
          example: ["corpo", "street_kid"]
    
    City:
      type: object
      required:
        - id
        - name
        - region
        - description
        - available_for_factions
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор города
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: Название города
          example: "Night City"
        region:
          type: string
          description: Регион/сервер
          example: "EU"
        description:
          type: string
          description: Описание города
          example: "Главный город, множество возможностей"
        available_for_factions:
          type: array
          description: Список доступных фракций для старта (UUID)
          items:
            type: string
            format: uuid
          example: ["550e8400-e29b-41d4-a716-446655440000"]

