openapi: 3.0.3
info:
  title: Contracts API
  version: 1.0.0
  description: |
    API для контрактов между игроками.
    
    Функционал:
    - 4 типа контрактов (exchange, service, courier, auction)
    - Escrow system (третья сторона)
    - Collateral (залог)
    - Reputation system integration
    - Dispute resolution & arbitration
    - Auto-execution
    - Contract templates
    - Multi-party contracts
    
    Типы контрактов:
    - EXCHANGE: обмен предметами/услугами
    - SERVICE: выполнение услуги за плату
    - COURIER: доставка с гарантией
    - AUCTION: аукцион с escrow
    
    Источник: .BRAIN/02-gameplay/economy/economy-contracts.md v1.0.0

  x-microservice:
    name: economy-service
    port: 8085
    domain: economy
    base-path: /api/v1/gameplay/economy
    package: com.necpgame.economyservice
servers:
  - url: https://api.necp.game/v1
    description: Production API Gateway
  - url: http://localhost:8080/api/v1
    description: Local API Gateway

tags:
  - name: Contracts
    description: Управление контрактами
  - name: Escrow
    description: Escrow система
  - name: Disputes
    description: Споры и арбитраж

paths:
  /gameplay/economy/contracts:
    get:
      summary: Получить список контрактов
      operationId: listContracts
      tags: [Contracts]
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum: [EXCHANGE, SERVICE, COURIER, AUCTION]
        - name: status
          in: query
          schema:
            type: string
            enum: [DRAFT, PENDING, ACTIVE, COMPLETED, CANCELLED, DISPUTED]
        - name: character_id
          in: query
          description: Фильтр по участнику
          schema:
            type: string
            format: uuid
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageNumber'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: Список контрактов
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginatedResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Contract'

    post:
      summary: Создать контракт
      operationId: createContract
      tags: [Contracts]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContractRequest'
      responses:
        '201':
          description: Контракт создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contract'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'

  /gameplay/economy/contracts/{contract_id}:
    get:
      summary: Получить детали контракта
      operationId: getContract
      tags: [Contracts]
      parameters:
        - name: contract_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Детали контракта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractDetailed'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'

  /gameplay/economy/contracts/{contract_id}/accept:
    post:
      summary: Принять контракт
      operationId: acceptContract
      tags: [Contracts]
      parameters:
        - name: contract_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                character_id:
                  type: string
                  format: uuid
                collateral:
                  type: integer
                  description: Залог (если требуется)
      responses:
        '200':
          description: Контракт принят
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'

  /gameplay/economy/contracts/{contract_id}/complete:
    post:
      summary: Завершить контракт
      operationId: completeContract
      tags: [Contracts]
      parameters:
        - name: contract_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                character_id:
                  type: string
                  format: uuid
                completion_proof:
                  type: object
                  description: Доказательство выполнения
                  additionalProperties: true
      responses:
        '200':
          description: Контракт завершен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractCompletionResult'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'

  /gameplay/economy/contracts/{contract_id}/cancel:
    post:
      summary: Отменить контракт
      operationId: cancelContract
      tags: [Contracts]
      parameters:
        - name: contract_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                character_id:
                  type: string
                  format: uuid
                reason:
                  type: string
      responses:
        '200':
          description: Контракт отменен
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'

  /gameplay/economy/contracts/{contract_id}/dispute:
    post:
      summary: Открыть спор по контракту
      operationId: openDispute
      tags: [Disputes]
      parameters:
        - name: contract_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisputeRequest'
      responses:
        '201':
          description: Спор открыт
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dispute'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'

  /gameplay/economy/contracts/escrow/{contract_id}:
    get:
      summary: Получить статус escrow
      operationId: getEscrowStatus
      tags: [Escrow]
      parameters:
        - name: contract_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Статус escrow
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EscrowStatus'

  /gameplay/economy/contracts/templates:
    get:
      summary: Получить шаблоны контрактов
      operationId: getContractTemplates
      tags: [Contracts]
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum: [EXCHANGE, SERVICE, COURIER, AUCTION]
      responses:
        '200':
          description: Шаблоны
          content:
            application/json:
              schema:
                type: object
                properties:
                  templates:
                    type: array
                    items:
                      $ref: '#/components/schemas/ContractTemplate'

  /gameplay/economy/contracts/character/{character_id}/active:
    get:
      summary: Получить активные контракты персонажа
      operationId: getActiveContracts
      tags: [Contracts]
      parameters:
        - name: character_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Активные контракты
          content:
            application/json:
              schema:
                type: object
                properties:
                  as_creator:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contract'
                  as_executor:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contract'

components:
  schemas:
    CreateContractRequest:
      type: object
      required:
        - creator_id
        - type
        - terms
      properties:
        creator_id:
          type: string
          format: uuid
        type:
          type: string
          enum: [EXCHANGE, SERVICE, COURIER, AUCTION]
        title:
          type: string
        description:
          type: string
        terms:
          $ref: '#/components/schemas/ContractTerms'
        payment:
          type: integer
        collateral_required:
          type: integer
          nullable: true
        deadline:
          type: string
          format: date-time
          nullable: true
        auto_execute:
          type: boolean
          default: true

    Contract:
      type: object
      properties:
        contract_id:
          type: string
          format: uuid
        type:
          type: string
          enum: [EXCHANGE, SERVICE, COURIER, AUCTION]
        title:
          type: string
        creator_id:
          type: string
          format: uuid
        executor_id:
          type: string
          format: uuid
          nullable: true
        status:
          type: string
          enum: [DRAFT, PENDING, ACTIVE, COMPLETED, CANCELLED, DISPUTED]
        payment:
          type: integer
        created_at:
          type: string
          format: date-time
        deadline:
          type: string
          format: date-time
          nullable: true

    ContractDetailed:
      allOf:
        - $ref: '#/components/schemas/Contract'
        - type: object
          properties:
            description:
              type: string
            terms:
              $ref: '#/components/schemas/ContractTerms'
            escrow:
              $ref: '#/components/schemas/EscrowStatus'
              nullable: true
            completion_proof:
              type: object
              nullable: true
            dispute:
              $ref: '#/components/schemas/Dispute'
              nullable: true
            history:
              type: array
              items:
                $ref: '#/components/schemas/ContractHistoryEntry'

    ContractTerms:
      type: object
      properties:
        deliverables:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum: [ITEM, SERVICE, DELIVERY, INFORMATION]
              item_id:
                type: string
                format: uuid
                nullable: true
              quantity:
                type: integer
                nullable: true
              description:
                type: string
        conditions:
          type: array
          items:
            type: object
            properties:
              condition_type:
                type: string
              description:
                type: string
              verification_method:
                type: string
                enum: [MANUAL, AUTO, ESCROW]
        penalties:
          type: object
          properties:
            late_completion:
              type: integer
            non_completion:
              type: integer
        bonuses:
          type: object
          properties:
            early_completion:
              type: integer
            quality_bonus:
              type: integer

    EscrowStatus:
      type: object
      properties:
        escrow_id:
          type: string
          format: uuid
        amount_held:
          type: integer
        collateral_held:
          type: integer
        release_conditions:
          type: array
          items:
            type: string
        held_items:
          type: array
          items:
            type: object
            properties:
              item_id:
                type: string
                format: uuid
              quantity:
                type: integer
        status:
          type: string
          enum: [HOLDING, RELEASING, RELEASED]

    DisputeRequest:
      type: object
      required:
        - character_id
        - reason
      properties:
        character_id:
          type: string
          format: uuid
        reason:
          type: string
        evidence:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              description:
                type: string
              data:
                type: string

    Dispute:
      type: object
      properties:
        dispute_id:
          type: string
          format: uuid
        contract_id:
          type: string
          format: uuid
        opened_by:
          type: string
          format: uuid
        reason:
          type: string
        status:
          type: string
          enum: [OPEN, UNDER_REVIEW, RESOLVED, REJECTED]
        resolution:
          type: string
          nullable: true
        resolved_by:
          type: string
          enum: [CREATOR, EXECUTOR, ARBITRATOR, AUTO]
          nullable: true
        opened_at:
          type: string
          format: date-time
        resolved_at:
          type: string
          format: date-time
          nullable: true

    ContractCompletionResult:
      type: object
      properties:
        contract_id:
          type: string
          format: uuid
        completed_at:
          type: string
          format: date-time
        payment_released:
          type: integer
        collateral_returned:
          type: integer
        reputation_changes:
          type: object
          properties:
            creator:
              type: integer
            executor:
              type: integer
        bonuses_applied:
          type: integer

    ContractTemplate:
      type: object
      properties:
        template_id:
          type: string
        name:
          type: string
        type:
          type: string
        description:
          type: string
        default_terms:
          $ref: '#/components/schemas/ContractTerms'
        popular:
          type: boolean

    ContractHistoryEntry:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        action:
          type: string
          enum: [CREATED, ACCEPTED, MODIFIED, COMPLETED, CANCELLED, DISPUTED, RESOLVED]
        character_id:
          type: string
          format: uuid
        details:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

