openapi: 3.0.3
info:
  title: Social Resonance Event Streams
  version: 1.0.0
  description: Асинхронные каналы social-service для индекса доверия, кампаний и обновлений связей.
servers:
  - url: kafka+ssl://kafka.internal.necpgame:9093
    description: Kafka кластер социальных событий
  - url: wss://api.necpgame.com/v1/social/resonance/stream
    description: WebSocket поток для UI `modules/social/resonance`
paths: {}
x-kafka-topics:
  social.resonance.indexChanged:
    summary: Индекс доверия изменился
    retentionHours: 168
    partitions: 6
    deliveryGuarantee: at-least-once
    payload:
      $ref: '../schemas/resonance-events-models.yaml#/components/schemas/SocialIndexChangedEvent'
  social.resonance.campaignStarted:
    summary: Запуск социальной кампании
    retentionHours: 120
    partitions: 6
    deliveryGuarantee: at-least-once
    payload:
      $ref: '../schemas/resonance-events-models.yaml#/components/schemas/SocialCampaignStartedEvent'
  social.resonance.relationshipUpdated:
    summary: Обновление романтической или альянсной связи
    retentionHours: 168
    partitions: 4
    deliveryGuarantee: at-least-once
    payload:
      $ref: '../schemas/resonance-events-models.yaml#/components/schemas/SocialRelationshipUpdatedEvent'
x-websocket:
  url: wss://api.necpgame.com/v1/social/resonance/stream
  heartbeatSeconds: 15
  reconnectPolicy: exponential
  auth:
    scheme: BearerAuth
    scopes:
      - social:resonance:read
  messages:
    indexSnapshot:
      summary: Текущее состояние индекса и World Pulse
      payload:
        $ref: '../schemas/resonance-models.yaml#/components/schemas/SocialResonanceSnapshot'
    campaignEvent:
      summary: Событие запуска кампании или симуляции
      payload:
        $ref: '../schemas/resonance-events-models.yaml#/components/schemas/SocialCampaignStartedEvent'
    relationshipEvent:
      summary: Актуализация романтических и гильдейских связей
      payload:
        $ref: '../schemas/resonance-events-models.yaml#/components/schemas/SocialRelationshipUpdatedEvent'
components:
  securitySchemes:
    BearerAuth:
      $ref: '../../shared/common/security.yaml#/components/securitySchemes/BearerAuth'

