openapi: 3.0.3
info:
  title: NPC Hiring Catalog API
  version: 1.0.0
  description: |
    API для каталога наймаемых NPC.
    
    Источник: .BRAIN/02-gameplay/social/npc-hiring-catalog.md v2.0.0
    
    13 NPC (T1-T5), legendary NPCs

servers:
  - url: https://api.necp.game/v1
    description: Production server

paths:
  /gameplay/social/npc-hiring-catalog:
    get:
      summary: Получить каталог NPC
      operationId: getNPCHiringCatalog
      parameters:
        - name: tier
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Каталог NPC
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    NPCCatalogEntry:
      type: object
      properties:
        npc_id:
          type: string
        tier:
          type: integer

