# Target Architecture:
# - Microservice: loot-service (port 8097)
# - API Base: /api/v1/loot
# - Dependencies: combat-service, quest-service, inventory-service, progression-service, analytics-service, notification-service, economy-service, party-service
# - Frontend Module: modules/gameplay/loot (useLootStore)
# - UI: LootDropModal, RollResultPanel, RaidLootSummary, LootHistoryList, LootProbabilityView, GuaranteedDropTracker
# - Forms: LootTableEditorForm, RollChoiceForm, LootDistributionForm
# - Hooks: useLootDrops, useLootHistory, useRollSystem, useLootTables

openapi: 3.0.3
info:
  title: Loot Generation Components
  version: 1.0.0
  description: Компоненты для Loot Generation API.

components:
  parameters:
    SourceId:
      name: sourceId
      in: path
      required: true
      description: Идентификатор источника лута.
      schema:
        type: string
    TableId:
      name: tableId
      in: path
      required: true
      description: Идентификатор таблицы лута.
      schema:
        type: string
    SessionId:
      name: sessionId
      in: path
      required: true
      description: Идентификатор сессии Need/Greed.
      schema:
        type: string
        format: uuid

  schemas:
    LootGenerationRequest:
      type: object
      required: [tableId, context]
      properties:
        tableId: { type: string }
        distributionHint: { type: string, enum: [PERSONAL, SHARED, RAID] }
        context: { $ref: '#/components/schemas/LootGenerationContext' }

    LootGenerationContext:
      type: object
      required: [sourceType, participants]
      properties:
        sourceType: { type: string, enum: [NPC, CONTAINER, EVENT, QUEST, RAID, WORLD_BOSS] }
        zoneId: { type: string }
        difficultyTier: { type: string, enum: [STORY, NORMAL, HARD, NIGHTMARE, LEGENDARY] }
        participants:
          type: array
          items: { $ref: '#/components/schemas/LootParticipant' }
        luckModifiers:
          type: object
          properties:
            personal: { type: number, format: float }
            party: { type: number, format: float }
            global: { type: number, format: float }
        eventFlags:
          type: array
          items: { type: string }
        killTimestamp: { type: string, format: date-time }
        seed: { type: string }

    LootParticipant:
      type: object
      required: [playerId, characterId]
      properties:
        playerId: { type: string, format: uuid }
        characterId: { type: string, format: uuid }
        level: { type: integer }
        contribution: { type: number, format: float }
        luckBonus: { type: number, format: float }
        role: { type: string }

    LootGenerationResult:
      type: object
      required: [resultId, distributionMode, items]
      properties:
        resultId: { type: string, format: uuid }
        distributionMode: { type: string, enum: [PERSONAL, SHARED, RAID, GUARANTEED] }
        items:
          type: array
          items: { $ref: './loot-advanced-components.yaml#/components/schemas/LootItem' }
        currency:
          type: array
          items: { $ref: '#/components/schemas/LootCurrency' }
        rollSessions:
          type: array
          items: { $ref: './loot-advanced-components.yaml#/components/schemas/LootRoll' }
        guarantees:
          type: array
          items: { $ref: '#/components/schemas/GuaranteedReward' }
        auditTrailId: { type: string, format: uuid }

    LootCurrency:
      type: object
      required: [type, amount]
      properties:
        type: { type: string, enum: [EDDIES, BATTLE_TOKEN, RAID_TOKEN, ARENA_POINT] }
        amount: { type: integer, minimum: 0 }

    GuaranteedReward:
      type: object
      required: [rewardId, templateId]
      properties:
        rewardId: { type: string, format: uuid }
        templateId: { type: string }
        description: { type: string }
        deliveryMode: { type: string, enum: [DIRECT, MAIL, VENDOR, TOKEN] }

    SimulationRequest:
      type: object
      required: [iterations]
      properties:
        iterations: { type: integer, minimum: 10, maximum: 5000 }
        context: { $ref: '#/components/schemas/LootGenerationContext' }
        metrics:
          type: array
          items: { type: string, enum: [RARITY_DISTRIBUTION, CURRENCY_EXPECTATION, TOKEN_DROP_RATE, PITY_TRIGGER] }

    SimulationResponse:
      type: object
      required: [iterations, results]
      properties:
        iterations: { type: integer }
        results:
          type: array
          items: { $ref: '#/components/schemas/SimulationBucket' }
        totalCurrency:
          type: array
          items: { $ref: '#/components/schemas/CurrencyExpectation' }

    SimulationBucket:
      type: object
      required: [key, probability]
      properties:
        key: { type: string }
        probability: { type: number, format: float }
        averageQuantity: { type: number, format: float }

    CurrencyExpectation:
      type: object
      required: [type, average]
      properties:
        type: { type: string }
        average: { type: number, format: float }

    LootTableSummary:
      type: object
      required: [tableId, name, tableType]
      properties:
        tableId: { type: string }
        name: { type: string }
        tableType: { type: string, enum: [NPC_LOOT, CONTAINER_LOOT, BOSS_LOOT, QUEST_REWARD, EVENT_LOOT] }
        sourceId: { type: string }
        levelRange: { type: string }
        rarityCurve: { type: string }
        active: { type: boolean }
        version: { type: string }

    LootTableListResponse:
      type: object
      required: [tables]
      properties:
        tables:
          type: array
          items: { $ref: '#/components/schemas/LootTableSummary' }
        page: { $ref: '../../shared/common/pagination.yaml#/components/schemas/Page' }

    LootTableUpsertRequest:
      type: object
      required: [tableId, name, tableType, entries]
      properties:
        tableId: { type: string }
        name: { type: string }
        tableType: { type: string, enum: [NPC_LOOT, CONTAINER_LOOT, BOSS_LOOT, QUEST_REWARD, EVENT_LOOT] }
        sourceId: { type: string }
        minItems: { type: integer }
        maxItems: { type: integer }
        currencyRange:
          type: object
          properties:
            min: { type: integer }
            max: { type: integer }
        rarityCurve: { type: string }
        modifiers:
          type: array
          items: { $ref: '#/components/schemas/LootModifier' }
        pityConfig: { $ref: '#/components/schemas/PityTimerConfig' }
        entries:
          type: array
          items: { $ref: '#/components/schemas/LootEntryDefinition' }

    LootEntryDefinition:
      type: object
      required: [entryId, templateId, weight]
      properties:
        entryId: { type: string }
        templateId: { type: string }
        weight: { type: integer, minimum: 1 }
        quantityRange:
          type: object
          properties:
            min: { type: integer, default: 1 }
            max: { type: integer, default: 1 }
        rarityOverride: { type: string }
        conditions:
          type: array
          items: { $ref: '#/components/schemas/LootCondition' }
        tags:
          type: array
          items: { type: string }

    LootCondition:
      type: object
      required: [type]
      properties:
        type: { type: string, enum: [FACTION, QUEST_STATE, EVENT_FLAG, PARTY_SIZE, ROLE, DIFFICULTY] }
        value: { type: string }
        operator: { type: string, enum: [EQUALS, NOT_EQUALS, GREATER, LESS, BETWEEN, IN] }

    LootEntryBatchRequest:
      type: object
      required: [entries]
      properties:
        entries:
          type: array
          items: { $ref: '#/components/schemas/LootEntryDefinition' }
        operation: { type: string, enum: [UPSERT, DELETE] }

    LootModifier:
      type: object
      required: [type]
      properties:
        type: { type: string, enum: [EVENT, SEASON, GLOBAL_BONUS, PERSONAL_LUCK, PARTY_AVERAGE] }
        value: { type: number, format: float }
        expiresAt: { type: string, format: date-time }

    PityTimerConfig:
      type: object
      properties:
        enabled: { type: boolean }
        threshold: { type: integer }
        rewardTemplateId: { type: string }
        resetMode: { type: string, enum: [ON_DROP, ON_SEASON, MANUAL] }

    PersonalDistributionRequest:
      type: object
      required: [resultId, playerId]
      properties:
        resultId: { type: string, format: uuid }
        playerId: { type: string, format: uuid }
        grantMode: { type: string, enum: [INVENTORY, MAIL, BANK] }

    SharedDistributionRequest:
      type: object
      required: [resultId, partyId]
      properties:
        resultId: { type: string, format: uuid }
        partyId: { type: string, format: uuid }
        threshold: { type: string, enum: [FREE_FOR_ALL, ROUND_ROBIN, MASTER_LOOTER] }
        autoAssignCommons: { type: boolean }
        rollConfig: { $ref: '#/components/schemas/RollConfig' }

    RaidDistributionRequest:
      type: object
      required: [resultId, raidId]
      properties:
        resultId: { type: string, format: uuid }
        raidId: { type: string, format: uuid }
        guaranteedTokens:
          type: array
          items: { $ref: '#/components/schemas/GuaranteedReward' }
        lootCouncil:
          type: array
          items: { type: string, format: uuid }

    GuaranteedDistributionRequest:
      type: object
      required: [playerId, reward]
      properties:
        playerId: { type: string, format: uuid }
        reward: { $ref: '#/components/schemas/GuaranteedReward' }
        trigger: { type: string, enum: [PITY_TIMER, MILESTONE, COMPENSATION] }

    DistributionResult:
      type: object
      required: [status]
      properties:
        status: { type: string, enum: [QUEUED, COMPLETED, FAILED] }
        grantedItems:
          type: array
          items: { $ref: './loot-advanced-components.yaml#/components/schemas/LootItem' }
        grantReference: { type: string }
        errors:
          type: array
          items: { $ref: '#/components/schemas/LootGenerationError' }

    RollConfig:
      type: object
      properties:
        timeoutSeconds: { type: integer, default: 60 }
        autoPassAfk: { type: boolean, default: true }
        allowNeedRoles:
          type: array
          items: { type: string }

    RollStartRequest:
      type: object
      required: [resultId, item]
      properties:
        resultId: { type: string, format: uuid }
        item: { $ref: './loot-advanced-components.yaml#/components/schemas/LootItem' }
        participants:
          type: array
          items: { $ref: './loot-advanced-components.yaml#/components/schemas/RollParticipant' }

    RollOutcome:
      type: object
      properties:
        winnerId: { type: string, format: uuid }
        reason: { type: string }
        rerollSuggested: { type: boolean }

    LootStatsResponse:
      type: object
      properties:
        dropRates:
          type: array
          items: { $ref: '#/components/schemas/SimulationBucket' }
        pityHeatmap:
          type: array
          items: { $ref: '#/components/schemas/PityTimerState' }
        rareDropNotifications: { type: integer }
        averageCompletionTime: { type: number, format: float }

    LootReserveRequest:
      type: object
      required: [resultId, item]
      properties:
        resultId: { type: string, format: uuid }
        item: { $ref: './loot-advanced-components.yaml#/components/schemas/LootItem' }
        target: { type: string, enum: [INVENTORY, MAIL, TRADE, VENDOR] }
        expiresAt: { type: string, format: date-time }

    LootReservationResponse:
      type: object
      required: [reservationId, status]
      properties:
        reservationId: { type: string, format: uuid }
        status: { type: string, enum: [ACTIVE, RELEASED, EXPIRED] }
        reservedItem: { $ref: './loot-advanced-components.yaml#/components/schemas/LootItem' }

    LootReleaseRequest:
      type: object
      required: [reservationId]
      properties:
        reservationId: { type: string, format: uuid }
        reason: { type: string }

    LootEventNotificationRequest:
      type: object
      required: [eventType, payload]
      properties:
        eventType: { type: string, enum: [RARE_DROP, WORLD_ANNOUNCEMENT, RAID_SUMMARY] }
        payload: { type: object, additionalProperties: true }

    PityTimerUpdateRequest:
      type: object
      required: [playerId, tableId]
      properties:
        playerId: { type: string, format: uuid }
        tableId: { type: string }
        action: { type: string, enum: [INCREMENT, RESET, FORCE_REWARD] }
        amount: { type: integer, default: 1 }
        rewardTemplateId: { type: string }

    PityTimerState:
      type: object
      required: [playerId, tableId, counter]
      properties:
        playerId: { type: string, format: uuid }
        tableId: { type: string }
        counter: { type: integer }
        threshold: { type: integer }
        guaranteedReward: { type: string }

    LootConfigResponse:
      type: object
      properties:
        globalModifiers:
          type: array
          items: { $ref: '#/components/schemas/LootModifier' }
        seasonalRules:
          type: array
          items:
            type: object
            properties:
              seasonId: { type: string }
              bonus: { type: number, format: float }
        dropCaps:
          type: array
          items:
            type: object
            properties:
              itemTemplateId: { type: string }
              weeklyCap: { type: integer }

    LootGenerationError:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          enum: [TABLE_NOT_FOUND, ENTRY_INVALID, ROLL_DUPLICATE, NO_ELIGIBLE_PLAYERS, RESERVATION_FAILED, PITY_DISABLED, CONFIG_LOCKED, DISTRIBUTION_ERROR]
        message: { type: string }
        details: { type: object, additionalProperties: true }

    LootRealtimeEvent:
      type: object
      required: [type, payload]
      properties:
        type: { type: string, enum: [loot-generated, loot-distributed, roll-updated, rare-drop, pity-triggered, loot-table-updated] }
        payload: { type: object, additionalProperties: true }


