openapi: 3.0.3
info:
  title: Canon Classes API
  version: 1.0.0
  description: |
    API для 10 классов из лора Cyberpunk.
    
    Источник: .BRAIN/02-gameplay/progression/classes-canon.md v1.0.0

servers:
  - url: https://api.necp.game/v1
    description: Production server

paths:
  /gameplay/progression/classes-canon:
    get:
      summary: Получить канонические классы
      operationId: getCanonClasses
      responses:
        '200':
          description: Список канонических классов
          content:
            application/json:
              schema:
                type: object
                properties:
                  classes:
                    type: array
                    items:
                      type: object

  /gameplay/progression/classes-canon/{class_id}/lore:
    get:
      summary: Получить лор класса
      operationId: getClassLore
      parameters:
        - name: class_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Лор класса
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    CanonClass:
      type: object
      properties:
        class_id:
          type: string
        name:
          type: string
        lore_source:
          type: string
        description:
          type: string

