openapi: 3.0.3
info:
  title: Game Start UI API
  version: 1.0.0
  description: API для UI старта игры (выбор класса, origin, внешности)
servers:
  - url: https://api.necp.game/v1
tags:
  - name: Game Start UI
paths:
  /gameplay/onboarding/game-start-ui:
    get:
      summary: Получить данные для UI старта игры
      operationId: getGameStartUI
      tags: [Game Start UI]
      responses:
        '200':
          description: Данные UI
          content:
            application/json:
              schema:
                type: object
components:
  schemas: {}


