# Equipment Matrix API - Endpoints рынков и заказных сборок
# Источник: .BRAIN/02-gameplay/economy/equipment-matrix.md (v1.0.0)
# Раздел: Endpoints для рынков, аукционов и заказных сборок

openapi: 3.0.3
info:
  title: Equipment Matrix - Markets & Orders Endpoints
  version: 1.0.0
  description: |
    Endpoints для рынков, аукционов и заказных сборок.
    Источник: .BRAIN/02-gameplay/economy/equipment-matrix.md (v1.0.0)

paths:
  # Рынки
  /gameplay/economy/markets/items:
    get:
      summary: Получить список предметов на рынке
      description: Возвращает список предметов на рынке с фильтрацией.
      operationId: listMarketItems
      tags:
        - Markets
      security:
        - BearerAuth: []
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum: [weapon, armor, implant, cyberdeck, mod]
          description: Тип предмета
        - name: subtype
          in: query
          schema:
            type: string
          description: Подтип предмета
        - name: rarity
          in: query
          schema:
            type: string
            enum: [common, uncommon, rare, epic, legendary, artifact]
          description: Редкость предмета
        - name: brand_id
          in: query
          schema:
            type: string
            format: uuid
          description: Идентификатор бренда
        - name: zone_tag
          in: query
          schema:
            type: string
          description: Тег зоны генерации
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/Page'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: Список предметов на рынке
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../equipment-matrix-markets.yaml#/components/schemas/MarketItem'
                  meta:
                    $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginationMeta'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/markets/items/{item_id}/list:
    post:
      summary: Выставить предмет на рынок
      description: Выставляет предмет на рынок.
      operationId: listItem
      tags:
        - Markets
      security:
        - BearerAuth: []
      parameters:
        - name: item_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор предмета
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/ListItemRequest'
      responses:
        '201':
          description: Предмет успешно выставлен на рынок
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-markets.yaml#/components/schemas/ListingResult'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '409':
          $ref: '../../shared/common/responses.yaml#/components/responses/Conflict'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  # Аукционы
  /gameplay/economy/auctions:
    get:
      summary: Получить список аукционов
      description: Возвращает список аукционов с фильтрацией.
      operationId: listAuctions
      tags:
        - Auctions
      security:
        - BearerAuth: []
      parameters:
        - name: rarity_min
          in: query
          schema:
            type: string
            enum: [common, uncommon, rare, epic, legendary, artifact]
          description: Минимальная редкость
        - name: status
          in: query
          schema:
            type: string
            enum: [active, closed, cancelled]
          description: Статус аукциона
        - name: item_type
          in: query
          schema:
            type: string
            enum: [weapon, armor, implant, cyberdeck, mod]
          description: Тип предмета
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/Page'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: Список аукционов
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../equipment-matrix-markets.yaml#/components/schemas/Auction'
                  meta:
                    $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginationMeta'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

    post:
      summary: Создать аукцион
      description: Создает аукцион для предмета (только для редкости ≥ epic).
      operationId: createAuction
      tags:
        - Auctions
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/CreateAuctionRequest'
      responses:
        '201':
          description: Аукцион успешно создан
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-markets.yaml#/components/schemas/Auction'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '409':
          $ref: '../../shared/common/responses.yaml#/components/responses/Conflict'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/auctions/{auction_id}/bid:
    post:
      summary: Сделать ставку на аукционе
      description: Делает ставку на аукционе.
      operationId: placeBid
      tags:
        - Auctions
      security:
        - BearerAuth: []
      parameters:
        - name: auction_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор аукциона
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/PlaceBidRequest'
      responses:
        '201':
          description: Ставка успешно сделана
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-markets.yaml#/components/schemas/BidResult'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '409':
          $ref: '../../shared/common/responses.yaml#/components/responses/Conflict'
        '422':
          $ref: '../../shared/common/responses.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  # Заказные сборки
  /gameplay/economy/custom-orders:
    get:
      summary: Получить список заказных сборок
      description: Возвращает список заказных сборок с фильтрацией.
      operationId: listCustomOrders
      tags:
        - Custom Orders
      security:
        - BearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, in_progress, completed, cancelled, failed]
          description: Статус заказа
        - name: client_id
          in: query
          schema:
            type: string
            format: uuid
          description: Идентификатор клиента
        - name: executor_id
          in: query
          schema:
            type: string
            format: uuid
          description: Идентификатор исполнителя
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/Page'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: Список заказных сборок
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../equipment-matrix-markets.yaml#/components/schemas/CustomOrder'
                  meta:
                    $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginationMeta'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

    post:
      summary: Создать заказную сборку
      description: Создает заказную сборку с указанной спецификацией, бюджетом и сроком.
      operationId: createCustomOrder
      tags:
        - Custom Orders
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/CreateCustomOrderRequest'
      responses:
        '201':
          description: Заказ успешно создан
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-markets.yaml#/components/schemas/CustomOrder'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/custom-orders/{order_id}/accept:
    post:
      summary: Принять заказную сборку к выполнению
      description: Принимает заказную сборку к выполнению исполнителем.
      operationId: acceptOrder
      tags:
        - Custom Orders
      security:
        - BearerAuth: []
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор заказа
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/AcceptOrderRequest'
      responses:
        '200':
          description: Заказ принят к выполнению (статус in_progress)
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-markets.yaml#/components/schemas/CustomOrder'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '409':
          $ref: '../../shared/common/responses.yaml#/components/responses/Conflict'
        '422':
          $ref: '../../shared/common/responses.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/custom-orders/{order_id}/fulfill:
    post:
      summary: Выполнить заказную сборку
      description: Выполняет заказную сборку с указанным предметом и KPI.
      operationId: fulfillOrder
      tags:
        - Custom Orders
      security:
        - BearerAuth: []
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор заказа
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/FulfillOrderRequest'
      responses:
        '200':
          description: Заказ успешно выполнен
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-markets.yaml#/components/schemas/FulfillResult'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '422':
          $ref: '../../shared/common/responses.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

