# Equipment Matrix API - Endpoints крафта и реролла
# Источник: .BRAIN/02-gameplay/economy/equipment-matrix.md (v1.0.0)
# Раздел: Endpoints для крафта и реролла

openapi: 3.0.3
info:
  title: Equipment Matrix - Crafting & Reroll Endpoints
  version: 1.0.0
  description: |
    Endpoints для крафта и реролла предметов.
    Источник: .BRAIN/02-gameplay/economy/equipment-matrix.md (v1.0.0)

paths:
  # Крафт
  /gameplay/economy/items/craft:
    post:
      summary: Создать предмет через крафт
      description: |
        Создает предмет через крафт по рецепту.
        Источник: .BRAIN/02-gameplay/economy/equipment-matrix.md -> Крафт
      operationId: craftItem
      tags:
        - Items
        - Crafting
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/CraftItemRequest'
      responses:
        '201':
          description: Предмет успешно создан через крафт
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-generation.yaml#/components/schemas/CraftResult'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '409':
          $ref: '../../shared/common/responses.yaml#/components/responses/Conflict'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/recipes:
    get:
      summary: Получить список рецептов крафта
      description: Возвращает список рецептов крафта с фильтрацией по типу предмета и качеству.
      operationId: listRecipes
      tags:
        - Crafting
        - Recipes
      security:
        - BearerAuth: []
      parameters:
        - name: item_type
          in: query
          schema:
            type: string
            enum: [weapon, armor, implant, cyberdeck, mod]
          description: Тип предмета
          example: "weapon"
        - name: quality
          in: query
          schema:
            type: string
            enum: [common, uncommon, rare, epic, legendary]
          description: Качество результата
          example: "rare"
        - name: player_id
          in: query
          schema:
            type: string
            format: uuid
          description: Идентификатор игрока (для проверки доступности)
          example: "550e8400-e29b-41d4-a716-446655440004"
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/Page'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: Список рецептов
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../equipment-matrix-generation.yaml#/components/schemas/CraftingRecipe'
                  meta:
                    $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginationMeta'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/recipes/{recipe_id}:
    get:
      summary: Получить информацию о рецепте
      description: Возвращает полную информацию о рецепте крафта.
      operationId: getRecipe
      tags:
        - Crafting
        - Recipes
      security:
        - BearerAuth: []
      parameters:
        - name: recipe_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор рецепта
      responses:
        '200':
          description: Информация о рецепте
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-generation.yaml#/components/schemas/CraftingRecipe'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/items/craft/validate:
    post:
      summary: Валидировать возможность крафта
      description: Проверяет возможность крафта предмета по рецепту с указанными компонентами.
      operationId: validateCraft
      tags:
        - Items
        - Crafting
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/ValidateCraftRequest'
      responses:
        '200':
          description: Результат валидации крафта
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-items.yaml#/components/schemas/ValidationResult'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  # Реролл
  /gameplay/economy/items/{item_id}/reroll:
    post:
      summary: Выполнить реролл предмета
      description: |
        Выполняет реролл предмета (частичный, полный или калибровка).
        Источник: .BRAIN/02-gameplay/economy/equipment-matrix.md -> Реролл/перековка
      operationId: rerollItem
      tags:
        - Items
        - Reroll
      security:
        - BearerAuth: []
      parameters:
        - name: item_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор предмета
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/RerollRequest'
      responses:
        '200':
          description: Реролл выполнен
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-generation.yaml#/components/schemas/RerollResult'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '422':
          $ref: '../../shared/common/responses.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/items/{item_id}/reroll/validate:
    post:
      summary: Валидировать возможность реролла
      description: Проверяет возможность реролла предмета в указанном режиме.
      operationId: validateReroll
      tags:
        - Items
        - Reroll
      security:
        - BearerAuth: []
      parameters:
        - name: item_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор предмета
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/ValidateRerollRequest'
      responses:
        '200':
          description: Результат валидации реролла
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-items.yaml#/components/schemas/ValidationResult'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/items/{item_id}/reroll/history:
    get:
      summary: Получить историю рероллов предмета
      description: Возвращает историю рероллов предмета с результатами.
      operationId: getRerollHistory
      tags:
        - Items
        - Reroll
      security:
        - BearerAuth: []
      parameters:
        - name: item_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор предмета
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/Page'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: История рероллов
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../equipment-matrix-generation.yaml#/components/schemas/RerollHistory'
                  meta:
                    $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginationMeta'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

