# Equipment Matrix API - Request/Response модели
# Источник: .BRAIN/02-gameplay/economy/equipment-matrix.md (v1.0.0)
# Задание: API-SWAGGER/tasks/active/queue/task-002-equipment-matrix-api.md
# Task ID: API-TASK-002

openapi: 3.0.3
info:
  title: Equipment Matrix - Request/Response Models
  version: 1.0.0

components:
  schemas:
    # Request модели для генерации
    GenerateItemRequest:
      type: object
      required:
        - type
        - subtype
      description: Запрос на генерацию предмета
      properties:
        type:
          type: string
          enum: [weapon, armor, implant, cyberdeck, mod]
          description: Тип предмета
        subtype:
          type: string
          description: Подтип предмета
        zone_tag:
          type: string
          nullable: true
          description: Тег зоны генерации
        league_id:
          type: string
          format: uuid
          nullable: true
          description: Идентификатор лиги
        rarity_hint:
          type: string
          enum: [common, uncommon, rare, epic, legendary, artifact]
          nullable: true
          description: Подсказка редкости (не гарантирует результат)
        brand_hint:
          type: string
          format: uuid
          nullable: true
          description: Подсказка бренда (не гарантирует результат)

    GenerateBatchRequest:
      type: object
      required:
        - count
        - type
      description: Запрос на генерацию нескольких предметов
      properties:
        count:
          type: integer
          minimum: 1
          maximum: 100
          description: Количество предметов для генерации
        type:
          type: string
          enum: [weapon, armor, implant, cyberdeck, mod]
          description: Тип предметов
        subtype:
          type: string
          nullable: true
          description: Подтип предметов
        zone_tag:
          type: string
          nullable: true
          description: Тег зоны генерации
        filters:
          type: object
          nullable: true
          description: Фильтры
          additionalProperties: true

    ValidateGenerationRequest:
      type: object
      required:
        - type
      description: Запрос на валидацию генерации
      properties:
        type:
          type: string
          enum: [weapon, armor, implant, cyberdeck, mod]
          description: Тип предмета
        zone_tag:
          type: string
          nullable: true
          description: Тег зоны
        rarity:
          type: string
          enum: [common, uncommon, rare, epic, legendary, artifact]
          nullable: true
          description: Желаемая редкость
        brand:
          type: string
          format: uuid
          nullable: true
          description: Желаемый бренд

    # Request модели для брендов
    CreateBrandRequest:
      type: object
      required:
        - name
        - origin
        - signature_bonuses
      description: Запрос на создание пользовательского бренда
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Название бренда
        visual_style:
          type: string
          nullable: true
          description: Визуальный стиль
        lore:
          type: string
          nullable: true
          description: Лор-описание бренда
        signature_bonuses:
          type: array
          items:
            type: object
          description: Сигнатурные бонусы (из разрешенных пулов)

    UpdateBrandRequest:
      type: object
      description: Запрос на обновление бренда (все поля опциональны)
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        visual_style:
          type: string
        lore:
          type: string
        signature_bonuses:
          type: array
          items:
            type: object

    # Request модели для крафта
    CraftItemRequest:
      type: object
      required:
        - recipe_id
        - components
        - player_id
      description: Запрос на крафт предмета
      properties:
        recipe_id:
          type: string
          format: uuid
          description: Идентификатор рецепта
          example: "cc0e8400-e29b-41d4-a716-446655440001"
        components:
          type: array
          items:
            type: object
            required:
              - item_id
              - quantity
            properties:
              item_id:
                type: string
                format: uuid
              quantity:
                type: integer
                minimum: 1
          description: Компоненты для крафта
        facilities:
          type: array
          items:
            type: string
          description: Используемые станции/оборудование
        player_id:
          type: string
          format: uuid
          description: Идентификатор игрока

    ValidateCraftRequest:
      type: object
      required:
        - recipe_id
        - components
        - player_id
      description: Запрос на валидацию крафта
      properties:
        recipe_id:
          type: string
          format: uuid
          description: Идентификатор рецепта
        components:
          type: array
          items:
            type: object
            required:
              - item_id
              - quantity
            properties:
              item_id:
                type: string
                format: uuid
              quantity:
                type: integer
                minimum: 1
          description: Компоненты для крафта
        player_id:
          type: string
          format: uuid
          description: Идентификатор игрока

    # Request модели для реролла
    RerollRequest:
      type: object
      required:
        - mode
      description: Запрос на реролл предмета
      properties:
        mode:
          type: string
          enum: [partial, full, calibrate]
          description: Режим реролла (частичный, полный, калибровка)
        component_ids:
          type: array
          items:
            type: string
            format: uuid
          nullable: true
          description: Идентификаторы компонентов для реролла (для partial режима)

    ValidateRerollRequest:
      type: object
      required:
        - mode
      description: Запрос на валидацию реролла
      properties:
        mode:
          type: string
          enum: [partial, full, calibrate]
          description: Режим реролла
          example: "partial"

    # Request модели для рынков
    ListItemRequest:
      type: object
      required:
        - item_id
        - price
        - currency
        - duration
      description: Запрос на выставление предмета на рынок
      properties:
        item_id:
          type: string
          format: uuid
          description: Идентификатор предмета
        price:
          type: number
          format: float
          minimum: 0
          description: Цена предмета
        currency:
          type: string
          description: Валюта
        duration:
          type: integer
          minimum: 1
          maximum: 168
          description: Длительность листинга в часах (максимум 7 дней)

    CreateAuctionRequest:
      type: object
      required:
        - item_id
        - starting_price
        - duration
        - format
      description: Запрос на создание аукциона
      properties:
        item_id:
          type: string
          format: uuid
          description: Идентификатор предмета
        starting_price:
          type: number
          format: float
          minimum: 0
          description: Стартовая цена
        reserve_price:
          type: number
          format: float
          nullable: true
          minimum: 0
          description: Резервная цена (опционально)
        duration:
          type: integer
          minimum: 1
          maximum: 168
          description: Длительность аукциона в часах (максимум 7 дней)
        format:
          type: string
          enum: [english, dutch, sealed_bid]
          description: Формат аукциона

    PlaceBidRequest:
      type: object
      required:
        - amount
        - currency
      description: Запрос на ставку на аукционе
      properties:
        amount:
          type: number
          format: float
          minimum: 0
          description: Сумма ставки
        currency:
          type: string
          description: Валюта

    # Request модели для заказных сборок
    CreateCustomOrderRequest:
      type: object
      required:
        - specification
        - budget
        - deadline
      description: Запрос на создание заказной сборки
      properties:
        specification:
          type: object
          description: Спецификация заказа (бренд, диапазоны статов, аффиксы, требования)
          additionalProperties: true
        budget:
          type: number
          format: float
          minimum: 0
          description: Бюджет заказа
        deadline:
          type: string
          format: date-time
          description: Крайний срок выполнения
        requirements:
          type: object
          nullable: true
          description: Дополнительные требования (лицензии, навыки, репутация)
          additionalProperties: true

    AcceptOrderRequest:
      type: object
      required:
        - executor_id
        - estimated_time
      description: Запрос на принятие заказа к выполнению
      properties:
        executor_id:
          type: string
          format: uuid
          description: Идентификатор исполнителя
        estimated_time:
          type: string
          format: date-time
          description: Оценка времени выполнения

    FulfillOrderRequest:
      type: object
      required:
        - created_item_id
      description: Запрос на выполнение заказа
      properties:
        created_item_id:
          type: string
          format: uuid
          description: Идентификатор созданного предмета
        kpi:
          type: object
          nullable: true
          description: Показатели выполнения (качество, срок, соответствие спецификации)
          additionalProperties: true

    # Request модели для расчета редкости
    CalculateRarityRequest:
      type: object
      required:
        - zone_tag
      description: Запрос на расчет редкости для зоны
      properties:
        zone_tag:
          type: string
          description: Тег зоны
        modifiers:
          type: array
          items:
            type: object
          nullable: true
          description: Модификаторы (PvP, экстракт, лига, фракция, события)

