# Equipment Matrix API - Endpoints брендов и аффиксов
# Источник: .BRAIN/02-gameplay/economy/equipment-matrix.md (v1.0.0)
# Раздел: Endpoints для управления брендами и аффиксами

openapi: 3.0.3
info:
  title: Equipment Matrix - Brands & Affixes Endpoints
  version: 1.0.0
  description: |
    Endpoints для управления брендами и аффиксами.
    Источник: .BRAIN/02-gameplay/economy/equipment-matrix.md (v1.0.0)

paths:
  # Управление брендами
  /gameplay/economy/brands:
    get:
      summary: Получить список брендов
      description: Возвращает список брендов с фильтрацией по происхождению, фракции и статусу.
      operationId: listBrands
      tags:
        - Brands
      security:
        - BearerAuth: []
      parameters:
        - name: origin
          in: query
          schema:
            type: string
            enum: [lore, authored, user]
          description: Происхождение бренда
          example: "lore"
        - name: faction_id
          in: query
          schema:
            type: string
            format: uuid
          description: Идентификатор фракции
          example: "990e8400-e29b-41d4-a716-446655440002"
        - name: status
          in: query
          schema:
            type: string
            enum: [active, suspended, pending]
          description: Статус бренда
          example: "active"
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/Page'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: Список брендов
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../equipment-matrix-brands-affixes.yaml#/components/schemas/Brand'
                  meta:
                    $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginationMeta'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

    post:
      summary: Создать новый пользовательский бренд
      description: |
        Создает новый пользовательский бренд (требует модерации).
        Источник: .BRAIN/02-gameplay/economy/equipment-matrix.md -> Пайплайн пользовательских брендов
      operationId: createBrand
      tags:
        - Brands
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/CreateBrandRequest'
      responses:
        '201':
          description: Бренд успешно создан (со статусом pending)
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-brands-affixes.yaml#/components/schemas/Brand'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/brands/{brand_id}:
    get:
      summary: Получить информацию о бренде
      description: Возвращает полную информацию о бренде.
      operationId: getBrand
      tags:
        - Brands
      security:
        - BearerAuth: []
      parameters:
        - name: brand_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор бренда
      responses:
        '200':
          description: Информация о бренде
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-brands-affixes.yaml#/components/schemas/Brand'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

    put:
      summary: Обновить бренд
      description: Обновляет бренд (только для пользовательских брендов).
      operationId: updateBrand
      tags:
        - Brands
      security:
        - BearerAuth: []
      parameters:
        - name: brand_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор бренда
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../equipment-matrix-requests.yaml#/components/schemas/UpdateBrandRequest'
      responses:
        '200':
          description: Бренд успешно обновлен
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-brands-affixes.yaml#/components/schemas/Brand'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: '../../shared/common/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/brands/{brand_id}/signatures:
    get:
      summary: Получить сигнатурные бонусы бренда
      description: Возвращает сигнатурные бонусы бренда.
      operationId: getBrandSignatures
      tags:
        - Brands
      security:
        - BearerAuth: []
      parameters:
        - name: brand_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор бренда
      responses:
        '200':
          description: Сигнатурные бонусы бренда
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../equipment-matrix-brands-affixes.yaml#/components/schemas/SignatureBonuses'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  # Управление аффиксами
  /gameplay/economy/affixes:
    get:
      summary: Получить список аффиксов
      description: Возвращает список аффиксов с фильтрацией по типу, типу предмета и требованию редкости.
      operationId: listAffixes
      tags:
        - Affixes
      security:
        - BearerAuth: []
      parameters:
        - name: kind
          in: query
          schema:
            type: string
            enum: [simple, set, unique]
          description: Тип аффикса
          example: "simple"
        - name: item_type
          in: query
          schema:
            type: string
            enum: [weapon, armor, implant, cyberdeck, mod]
          description: Тип предмета
          example: "weapon"
        - name: rarity_requirement
          in: query
          schema:
            type: string
            enum: [common, uncommon, rare, epic, legendary, artifact]
          description: Требование к редкости
          example: "rare"
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/Page'
        - $ref: '../../shared/common/pagination.yaml#/components/parameters/PageSize'
      responses:
        '200':
          description: Список аффиксов
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../equipment-matrix-brands-affixes.yaml#/components/schemas/Affix'
                  meta:
                    $ref: '../../shared/common/pagination.yaml#/components/schemas/PaginationMeta'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/affixes/{affix_id}:
    get:
      summary: Получить информацию об аффиксе
      description: Возвращает полную информацию об аффиксе.
      operationId: getAffix
      tags:
        - Affixes
      security:
        - BearerAuth: []
      parameters:
        - name: affix_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор аффикса
      responses:
        '200':
          description: Информация об аффиксе
          content:
            application/json:
              schema:
                $ref: '../equipment-matrix-brands-affixes.yaml#/components/schemas/Affix'
        '404':
          $ref: '../../shared/common/responses.yaml#/components/responses/NotFound'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

  /gameplay/economy/affixes/pools:
    get:
      summary: Получить пулы аффиксов по типам предметов
      description: Возвращает пулы аффиксов с весами для указанного типа предмета и зоны.
      operationId: getAffixPools
      tags:
        - Affixes
      security:
        - BearerAuth: []
      parameters:
        - name: item_type
          in: query
          required: true
          schema:
            type: string
            enum: [weapon, armor, implant, cyberdeck, mod]
          description: Тип предмета
          example: "weapon"
        - name: zone_tag
          in: query
          schema:
            type: string
          description: Тег зоны (опционально)
          example: "downtown"
      responses:
        '200':
          description: Пулы аффиксов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../equipment-matrix-brands-affixes.yaml#/components/schemas/AffixPool'
        '400':
          $ref: '../../shared/common/responses.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/common/responses.yaml#/components/responses/InternalServerError'

